Salary Recommendation based on experience, test_score, interview_score and number of years of experience

In [135]:
#Importing required models
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math
from sklearn import linear_model

In [136]:
#Importing dataset

df = pd.read_excel("hiring.xlsx")
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary
0        NaN                    8.0                           9   50000
1        NaN                    8.0                           6   45000
2       five                    6.0                           7   60000
3        two                   10.0                          10   65000
4      seven                    9.0                           6   70000
5      three                    7.0                          10   62000
6        ten                    NaN                           7   72000
7     eleven                    7.0                           8   80000

Data Cleaning

In [138]:
#Experience can be assumed as 0 & the test_score can be asumed as median
print(df["test_score(out of 10)"].mean())
print(df["test_score(out of 10)"].median())
print(df["test_score(out of 10)"].mode())

7.857142857142857
8.0
0    7.0
1    8.0
Name: test_score(out of 10), dtype: float64

In [139]:
#Since this are the test scores, we can go with the median value as it is lower than the mean for error handling

df['test_score(out of 10)'] = df ['test_score(out of 10)'].fillna(math.floor(df["test_score(out of 10)"].mean()))

In [140]:
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary
0        NaN                    8.0                           9   50000
1        NaN                    8.0                           6   45000
2       five                    6.0                           7   60000
3        two                   10.0                          10   65000
4      seven                    9.0                           6   70000
5      three                    7.0                          10   62000
6        ten                    7.0                           7   72000
7     eleven                    7.0                           8   80000

In [141]:
df['experience'] = df['experience'].fillna("zero")

In [142]:
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary
0       zero                    8.0                           9   50000
1       zero                    8.0                           6   45000
2       five                    6.0                           7   60000
3        two                   10.0                          10   65000
4      seven                    9.0                           6   70000
5      three                    7.0                          10   62000
6        ten                    7.0                           7   72000
7     eleven                    7.0                           8   80000

In [143]:
from word2number import w2n

In [144]:
df.experience = df.experience.apply(w2n.word_to_num)
df

   experience  test_score(out of 10)  interview_score(out of 10)  salary
0           0                    8.0                           9   50000
1           0                    8.0                           6   45000
2           5                    6.0                           7   60000
3           2                   10.0                          10   65000
4           7                    9.0                           6   70000
5           3                    7.0                          10   62000
6          10                    7.0                           7   72000
7          11                    7.0                           8   80000

In [145]:
reg = linear_model.LinearRegression()
reg.fit(df[["experience", "test_score(out of 10)", "interview_score(out of 10)"]], df["salary"])

LinearRegression()

In [146]:
reg.predict([[2, 9, 6]])

C:\Users\pavan.vasa\AppData\Local\Anaconda3.1\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([53713.86677124])

In [147]:
reg_ = linear_model.LinearRegression()
reg_.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary'])
reg_.predict([[10,10,10]])

C:\Users\pavan.vasa\AppData\Local\Anaconda3.1\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([87903.25825647])